# Generated by Django 5.1.5 on 2025-05-05 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_user'),
        ('products', '0006_alter_productvariant_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
    ]
