# Generated by Django 5.0.4 on 2024-12-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_color_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
