# Generated by Django 5.0.4 on 2024-06-26 19:59

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_sizes_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
