# Generated by Django 5.0.4 on 2024-06-27 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
